keys:
  - &ywxt_work age17ymsfehq879pngqxza2tjjxhaqyqwss642rd3zeq059azzfym99sz0v4dz
  - &ywxt_ws age13f5yfwndfgd63hrjcz8lt253t6ju24w985fd5n4el06m9euz4quqqqw4ew
  - &recovery age1pjm0aaccxj5r67zrxt6ypluy2w53pd086u2768meu5nnzyzp6sdsgugg9x

creation_rules:
  - path_regex: secrets/host-keys/.*
    key_groups:
      - age:
          - *recovery
  - path_regex: secrets/ywxt-work-opencode\.yaml$
    key_groups:
      - age:
          - *ywxt_work
          - *ywxt_ws
          - *recovery
  - path_regex: secrets/ywxt-work-univpn\.yaml$
    key_groups:
      - age:
          - *ywxt_work
          - *recovery
